Feat/bait dropped on tilling or planting
Alathra/AlathraExtras pull request #122
Opened 2024-09-16 20:29 UTC by Xavbeat03

It's looking pretty good. It uses the dependency to ensure that the command is only run when the plugin is installed. Only concern is how the command looks in logs. Example of situation below:
![image](https://github.com/user-attachments/assets/c810a547-6f25-40b2-96ea-f5beb25f4493)

2024-09-16 20:32 UTC, Xavbeat03 commented
Unfortunately, I couldn't get the CFishing API access to work properly with the Alathra version of CFishing, so this is the workaround used.

2024-09-17 00:33 UTC, darksaid98 requested changes

2024-09-17 00:33 UTC, darksaid98 commented on src/main/java/me/ShermansWorld/AlathraExtras/AlathraExtras.java
> +        this.getServer().getPluginManager().registerEvents(new FarmingListener(), this);
This entire listener should be skipped at registration time, rather than inside the listener's executor method.

```suggestion
        this.getServer().getPluginManager().registerEvents(new FoodConsumeListener(), this);
        if (getServer().getPluginManager().isPluginEnabled("CustomFishing"))
            this.getServer().getPluginManager().registerEvents(new FarmingListener(), this);
```

2024-09-17 00:33 UTC, darksaid98 commented on src/main/java/me/ShermansWorld/AlathraExtras/AlathraExtras.java
> +        }
```suggestion
        // Attempt to initialize the customFishingPlugin variable
        if (getServer().getPluginManager().isPluginEnabled("CustomFishing")) {
            customFishingPlugin = BukkitCustomFishingPlugin.getInstance();
            if (customFishingPlugin == null) {
                getLogger().warning("Failed to initialize CustomFishing plugin hook.");
            } else {
                getLogger().info("CustomFishing plugin hook initialized successfully.");
            }
        } else {
            getLogger().warning("Failed to initialize CustomFishing plugin hook. CustomFishing could not be found on this server.");
        }
```

2024-09-17 00:33 UTC, darksaid98 commented on src/main/java/me/ShermansWorld/AlathraExtras/farming/FarmingListener.java
> +        if (AlathraExtras.customFishingPlugin == null) {
This should no longer happen, but the check has no significant performance impact, so you might as well leave it.

2024-09-17 00:36 UTC, darksaid98 commented
The only relevant change is skipping the registration of the listener if the plugin dependency isn't loaded. _(Let's be honest, there are a hundred things in this codebase that would break before your code.)_

Go ahead and merge after you've had a look at the requested changes. Awesome job as always 👍

2024-09-17 22:41 UTC, merged