feat: disabled eggs being thrown by dispensers
Alathra/AlathraExtras pull request #27
Opened 2023-12-16 19:35 UTC by rooooose-b

2023-12-16 19:37 UTC, rooooose-b commented
Using `dropItem` to spawn in the egg was the best I could find, though it looks a bit strange when they spawn in. `dropItemNaturally` could potentially be better, but then they could be thrown towards the dispenser which would also look weird. There's probably a better solution that I just didn't think of when making this.

2023-12-17 04:32 UTC, darksaid98 requested changes
Not a fan of how the item is dropped. Would it be possible to copy the velocity and position of the egg projectile and apply it to the item? It would shoot them really far but at least they wouldn't hatch. 

You might also be able to delete the projectile without canceling the entire event (*Which would then allow you to rely on the original item consumption mechanic*).

2023-12-17 04:32 UTC, darksaid98 commented on src/main/java/me/ShermansWorld/AlathraExtras/disabledispensereggs/DispenserListener.java
> +        if (e.getBlock().getType() == Material.DISPENSER) {
```suggestion
        if (e.getBlock().getType().equals(Material.DISPENSER)) {
```

2023-12-17 04:32 UTC, darksaid98 commented on src/main/java/me/ShermansWorld/AlathraExtras/disabledispensereggs/DispenserListener.java
> +            if (e.getItem().getType() == Material.EGG) {
```suggestion
            if (e.getItem().getType().equals(Material.EGG)) {
```

2023-12-17 15:38 UTC, darksaid98 requested changes
Other than that, looks good. Exceptional work with the PR's.

2023-12-17 15:38 UTC, darksaid98 commented on src/main/java/me/ShermansWorld/AlathraExtras/disabledispensereggs/DispenserListener.java
> +                Bukkit.getLogger().info("Egg detected.");
```suggestion
```
Let's leave the debug log out :)

2023-12-17 18:21 UTC, darksaid98 approved these changes

2023-12-19 01:25 UTC, merged